# Generated by Django 5.2.9 on 2026-01-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hutong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('history', models.TextField(verbose_name='历史')),
                ('image', models.URLField(verbose_name='图片URL')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
            ],
            options={
                'verbose_name': '胡同',
                'verbose_name_plural': '胡同',
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('historic', '历史古迹'), ('shop', '特色店铺'), ('food', '美食餐饮'), ('culture', '文化场所'), ('scenic', '景观')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('brief', models.CharField(max_length=200, verbose_name='简介')),
                ('images', models.JSONField(default=list, verbose_name='图片URL列表')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='api.hutong', verbose_name='所属胡同')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('duration', models.IntegerField(verbose_name='预计时长(分钟)')),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.hutong', verbose_name='所属胡同')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线',
            },
        ),
        migrations.CreateModel(
            name='RoutePOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poi', verbose_name='景点')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_pois', to='api.route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '路线景点',
                'verbose_name_plural': '路线景点',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poi', verbose_name='景点')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'unique_together': {('user', 'poi')},
            },
        ),
    ]
