# Generated by Django 5.2.9 on 2026-01-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hutong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='胡同名称')),
                ('description', models.TextField(verbose_name='胡同简介')),
                ('history', models.TextField(blank=True, verbose_name='历史背景')),
                ('location', models.CharField(max_length=200, verbose_name='地理位置')),
                ('image', models.ImageField(blank=True, upload_to='hutong/', verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '胡同',
                'verbose_name_plural': '胡同',
            },
        ),
        migrations.CreateModel(
            name='POICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(default='fa-map-marker', max_length=50, verbose_name='图标')),
            ],
            options={
                'verbose_name': 'POI分类',
                'verbose_name_plural': 'POI分类',
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(verbose_name='简介')),
                ('detail', models.TextField(blank=True, verbose_name='详细介绍')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('image', models.ImageField(blank=True, upload_to='poi/', verbose_name='图片')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='开放时间')),
                ('ticket_price', models.CharField(blank=True, max_length=100, verbose_name='门票价格')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='tour.hutong', verbose_name='所属胡同')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.poicategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': 'POI景点',
                'verbose_name_plural': 'POI景点',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='路线名称')),
                ('description', models.TextField(verbose_name='路线简介')),
                ('duration', models.CharField(max_length=50, verbose_name='预计时长')),
                ('distance', models.CharField(blank=True, max_length=50, verbose_name='路线长度')),
                ('difficulty', models.CharField(default='简单', max_length=20, verbose_name='难度')),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tour.hutong', verbose_name='所属胡同')),
            ],
            options={
                'verbose_name': '推荐路线',
                'verbose_name_plural': '推荐路线',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('tips', models.TextField(blank=True, verbose_name='游览提示')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.poi', verbose_name='关联POI')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tour.route', verbose_name='所属路线')),
            ],
            options={
                'verbose_name': '路线点',
                'verbose_name_plural': '路线点',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, verbose_name='会话标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.poi', verbose_name='收藏的POI')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'unique_together': {('poi', 'session_key')},
            },
        ),
    ]
