# Generated by Django 6.0 on 2026-01-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hutong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='胡同名称')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('location', models.CharField(max_length=200, verbose_name='地理位置')),
                ('history', models.TextField(verbose_name='历史沿革')),
                ('features', models.JSONField(default=list, verbose_name='特色标签')),
                ('image', models.CharField(max_length=500, verbose_name='封面图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '胡同',
                'verbose_name_plural': '胡同',
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('type', models.CharField(choices=[('historic', '历史古迹'), ('celebrity', '名人故居'), ('shop', '特色店铺'), ('food', '美食餐饮'), ('culture', '文化场所'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('brief', models.CharField(max_length=200, verbose_name='简短描述')),
                ('location', models.CharField(max_length=200, verbose_name='具体位置')),
                ('coordinates', models.JSONField(blank=True, null=True, verbose_name='坐标')),
                ('images', models.JSONField(default=list, verbose_name='图片列表')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='开放时间')),
                ('tips', models.CharField(blank=True, max_length=200, verbose_name='游览提示')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='tourism.hutong')),
            ],
            options={
                'verbose_name': '兴趣点',
                'verbose_name_plural': '兴趣点',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='路线名称')),
                ('description', models.TextField(verbose_name='路线介绍')),
                ('duration', models.CharField(max_length=50, verbose_name='预计时间')),
                ('distance', models.CharField(max_length=50, verbose_name='路线长度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hutong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tourism.hutong')),
            ],
            options={
                'verbose_name': '推荐路线',
                'verbose_name_plural': '推荐路线',
            },
        ),
        migrations.CreateModel(
            name='RoutePOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.poi')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_pois', to='tourism.route')),
            ],
            options={
                'verbose_name': '路线景点',
                'verbose_name_plural': '路线景点',
                'ordering': ['order'],
                'unique_together': {('route', 'poi')},
            },
        ),
    ]
